'use strict';
const DATA=window.REVIEW,SELECTED=window.PRIORITY,KEY='nltk-priority-v1',byId=id=>document.getElementById(id);
const bank={...DATA.questions,...Object.fromEntries(DATA.archive.map(q=>[q.id,q]))};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,sourceHash:SELECTED.sourceHash,answers:{},revealed:{}};
function validate(x){
 if(!x||x.version!==1||x.sourceHash!==SELECTED.sourceHash||!x.answers||!x.revealed)throw Error('Tệp tiến độ không thuộc mục này.');
 const clean={version:1,sourceHash:SELECTED.sourceHash,answers:{},revealed:{}};
 for(const item of SELECTED.items){const a=x.answers[item.id];if(a!==undefined){if(!item.gradable||!bank[item.id].options.some(o=>o.label===a))throw Error('Lựa chọn không hợp lệ.');clean.answers[item.id]=a;}if(x.revealed[item.id]===true)clean.revealed[item.id]=true;}
 return clean;
}
try{const old=localStorage.getItem(KEY);if(old)state=validate(JSON.parse(old));}catch(e){byId('saveNotice').textContent='Không đọc được tiến độ; bản lưu cũ vẫn được giữ.';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));byId('saveNotice').textContent='Đã lưu trên trình duyệt.';}catch(e){byId('saveNotice').textContent='Hãy xuất tiến độ để sao lưu.';}}
function math(root){root.querySelectorAll('[data-tex]').forEach(el=>katex.render(el.dataset.tex,el,{displayMode:true,throwOnError:false,strict:false}));renderMathInElement(root,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false,strict:false});}
function card(item,i){const q=bank[item.id],shown=!!state.revealed[item.id],a=state.answers[item.id];return `<div class="question-head"><h3>Câu/mảnh ${i+1} <span class="badge">${item.id}</span><span class="badge ${item.gradable?'':'problem'}">${item.gradable?'Có thể chấm':'Thiếu / lỗi / bản lặp'}</span></h3></div><div class="source-stem">${item.rawHtml}</div>${item.gradable?`<fieldset class="pick-options" style="border:0;padding:0"><legend>Chọn đáp án</legend>${q.options.map(o=>`<label class="option ${shown?(o.label===q.solution.answer?'correct-option':o.label===a?'wrong-option':''):''}"><input type="radio" name="${item.id}" value="${o.label}" ${a===o.label?'checked':''} ${shown?'disabled':''}><span>Chọn ${o.label}</span></label>`).join('')}</fieldset>`:'<p class="fine">Mục này không tính điểm. Bấm xem phân tích để kiểm tra kết quả, lỗi nguồn hoặc giả thiết cần dùng.</p>'}<div class="tools"><button class="primary" data-reveal="${item.id}" ${shown?'disabled':''}>${shown?'Đã mở lời giải':item.gradable?'Xem kết quả & lời giải':'Xem phân tích / lời giải'}</button>${item.gradable?`<button data-reset="${item.id}">Làm lại câu này</button>`:''}</div>${shown?`${item.gradable?`<p class="result-note"><strong>${a?(a===q.solution.answer?'Bạn chọn '+a+' · Đúng':'Bạn chọn '+a+' · Sai'):'Bạn chưa chọn đáp án'} · Đáp án đúng: ${q.solution.answer}</strong></p>`:`<p class="notice">${esc(q.note)} Kết luận có điều kiện được nêu ở các bước bên dưới.</p>`}<section class="solution">${q.solutionHtml}</section>`:''}`;}
function update(){const valid=SELECTED.items.filter(x=>x.gradable),done=valid.filter(x=>state.revealed[x.id]),right=done.filter(x=>state.answers[x.id]===bank[x.id].solution.answer).length;byId('priorityScore').innerHTML=`<strong>${right}/${done.length} câu đã xem kết quả đúng</strong><p>Đã chọn ${Object.keys(state.answers).length}/34 câu có thể chấm · Đã mở ${SELECTED.items.filter(x=>state.revealed[x.id]).length}/55 lời giải/phân tích. 21 mục thiếu/lỗi/bản lặp không tính điểm.</p>`;byId('priorityNav').innerHTML=SELECTED.items.map((x,i)=>`<button data-jump="${i+1}" class="${state.revealed[x.id]?(x.gradable?(state.answers[x.id]===bank[x.id].solution.answer?'correct':'wrong'):'answered'):state.answers[x.id]?'answered':''}" aria-label="Câu/mảnh ${i+1}">${i+1}</button>`).join('');}
function renderOne(id){const i=SELECTED.items.findIndex(x=>x.id===id);const el=byId('priority-'+id);el.innerHTML=card(SELECTED.items[i],i);math(el);update();}
function render(){byId('priorityList').innerHTML=SELECTED.items.map((x,i)=>`<article class="question" id="priority-${x.id}" data-question="${x.id}">${card(x,i)}</article>`).join('');math(byId('priorityList'));update();}
function confirmAction(title,text,action){byId('confirmTitle').textContent=title;byId('confirmText').textContent=text;byId('confirmDialog').showModal();byId('confirmOk').onclick=()=>{byId('confirmDialog').close();action();};}
byId('confirmCancel').onclick=()=>byId('confirmDialog').close();
byId('priorityList').onchange=e=>{if(e.target.type!=='radio'||state.revealed[e.target.name])return;state.answers[e.target.name]=e.target.value;save();update();};
byId('priorityList').onclick=e=>{const reveal=e.target.closest('[data-reveal]'),reset=e.target.closest('[data-reset]');if(reveal){const id=reveal.dataset.reveal;state.revealed[id]=!state.revealed[id];save();renderOne(id);}if(reset){const id=reset.dataset.reset;delete state.answers[id];delete state.revealed[id];save();renderOne(id);}};
byId('priorityNav').onclick=e=>{const b=e.target.closest('[data-jump]');if(b)byId('priority-'+SELECTED.items[Number(b.dataset.jump)-1].id).scrollIntoView({behavior:'smooth',block:'start'});};
byId('submitAll').onclick=()=>confirmAction('Mở lời giải toàn bộ 55 mục','Các câu chưa chọn được ghi nhận là bỏ trống. 21 mục thiếu/lỗi/bản lặp chỉ mở phân tích, không tính điểm.',()=>{for(const x of SELECTED.items)state.revealed[x.id]=true;save();render();byId('priorityScore').scrollIntoView({block:'start'});});
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
byId('exportPriority').onclick=()=>download('tien-do-cau-de-ra.json',JSON.stringify(state,null,2));
byId('importPriority').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const candidate=validate(JSON.parse(await file.text()));confirmAction('Nhập tiến độ','Thay tiến độ riêng của mục Câu dễ ra bằng tệp vừa chọn.',()=>{state=candidate;save();render();});}catch(err){byId('saveNotice').textContent=err.message;}e.target.value='';};
render();

let modalDeck=null,modalPage=1;
document.getElementById('zoomImage').onclick=()=>{const im=document.querySelector('#modalBody img');if(!im)return;const large=im.dataset.large==='true';im.dataset.large=String(!large);im.style.width=large?'100%':Math.max(im.naturalWidth,750)+'px';document.getElementById('zoomImage').textContent=large?'Phóng lớn':'Vừa cửa sổ';};
function showImage(key,title){modalDeck=null;document.getElementById('modalTitle').textContent=title;document.getElementById('slideNav').hidden=true;document.getElementById('sourceFilename').textContent='Ảnh trích từ tài liệu nguồn; chữ và số liệu giữ nguyên.';document.getElementById('modalBody').innerHTML='';const im=document.createElement('img');im.src=DATA.assets[key];im.alt=title;document.getElementById('modalBody').append(im);const dlg=document.getElementById('sourceDialog');if(!dlg.open)dlg.showModal();}
function showSlide(deck,page){modalDeck=Number(deck);modalPage=Number(page);const source=DATA.sources.find(s=>s.chapter===modalDeck);if(!source||!DATA.slides[deck+':'+page])return;document.getElementById('modalTitle').textContent='Slide chương '+deck+' · trang '+page+' / '+source.slides;document.getElementById('sourceFilename').textContent=source.source;document.getElementById('slideNav').hidden=false;document.getElementById('slidePage').innerHTML=Array.from({length:source.slides},(_,i)=>'<option value="'+(i+1)+'" '+(i+1===Number(page)?'selected':'')+'>Trang '+(i+1)+'</option>').join('');document.getElementById('slidePrev').disabled=Number(page)===1;document.getElementById('slideNext').disabled=Number(page)===source.slides;document.getElementById('modalBody').innerHTML='';const im=document.createElement('img');im.src=DATA.assets[DATA.slides[deck+':'+page]];im.alt='Slide chương '+deck+', trang '+page;document.getElementById('modalBody').append(im);const dlg=document.getElementById('sourceDialog');if(!dlg.open)dlg.showModal();dlg.scrollTop=0;}
document.addEventListener('click',e=>{const ref=e.target.closest('[data-ref]');if(ref){const [d,p]=ref.dataset.ref.split(':');showSlide(d,p);}});document.getElementById('closeModal').onclick=()=>document.getElementById('sourceDialog').close();document.getElementById('slidePrev').onclick=()=>showSlide(modalDeck,modalPage-1);document.getElementById('slideNext').onclick=()=>showSlide(modalDeck,modalPage+1);document.getElementById('slidePage').onchange=e=>showSlide(modalDeck,Number(e.target.value));document.getElementById('sourceDialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const box=e.currentTarget.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)e.currentTarget.close();}});
