'use strict';
const DATA=window.REVIEW,KEY='nltk-review-exams-v1',byId=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let progress={version:1,sourceHash:DATA.sourceHash,exams:{},marks:{}},current=null,storageOk=true;
function validateProgress(x){
 if(!x||x.version!==1||x.sourceHash!==DATA.sourceHash||!x.exams||typeof x.exams!=='object')throw Error('Tệp không thuộc bộ đề này hoặc sai định dạng.');
 const clean={version:1,sourceHash:DATA.sourceHash,exams:{},marks:{}};
 for(const e of DATA.exams){const s=x.exams[e.id];if(!s)continue;
  if(!s.answers||typeof s.answers!=='object'||typeof s.submitted!=='boolean'||typeof s.timed!=='boolean'||!Number.isFinite(s.started)||s.started<0||s.started>Date.now()+60000)throw Error('Dữ liệu phiên làm đề không hợp lệ.');
  const answers={};for(const k of e.ids){const a=s.answers[k];if(a!==undefined){if(!DATA.questions[k].options.some(o=>o.label===a))throw Error('Đáp án lưu không hợp lệ.');answers[k]=a;}}
  clean.exams[e.id]={answers,submitted:s.submitted,timed:s.timed,started:s.started,finished:Number.isFinite(s.finished)?s.finished:null};
 }
 if(x.marks&&typeof x.marks==='object')for(const k of Object.keys(DATA.questions))if(x.marks[k]===true)clean.marks[k]=true;
 return clean;
}
try{const old=localStorage.getItem(KEY);if(old)progress=validateProgress(JSON.parse(old));}catch(e){storageOk=false;byId('saveNotice').textContent='Không đọc được tiến độ cũ; hãy xuất bản hiện tại để sao lưu.';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageOk=true;byId('saveNotice').textContent='Đã lưu trên trình duyệt.';}catch(e){storageOk=false;byId('saveNotice').textContent='Trình duyệt không cho lưu. Hãy dùng Xuất tiến độ.';}}
function math(root){if(!window.katex)return;root.querySelectorAll('[data-tex]').forEach(el=>{if(!el.childElementCount)katex.render(el.dataset.tex,el,{displayMode:true,throwOnError:false,strict:false});});if(window.renderMathInElement)renderMathInElement(root,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false,strict:false});}
function score(e,s){return e.ids.filter(k=>s.answers[k]===DATA.questions[k].solution.answer).length;}
function home(){byId('examGrid').innerHTML=DATA.exams.map(e=>{const s=progress.exams[e.id];return `<article class="exam-card"><h2>${e.title}</h2><span class="badge">${e.theory} lý thuyết</span><span class="badge">${e.calculation} tính toán</span><p>${e.source} câu nguồn · ${e.generated} câu tự sinh</p><p>${s?(s.submitted?`Đã nộp · ${score(e,s)}/20 đúng`:`Đang làm · ${Object.keys(s.answers).length}/20 đã chọn`):'Chưa bắt đầu'}</p><button class="primary" data-exam="${e.id}">${s?(s.submitted?'Xem kết quả & lời giải':'Tiếp tục làm đề'):'Bắt đầu đề'}</button></article>`;}).join('');}
const c=DATA.counts;
byId('countsNote').innerHTML=`<p><strong>${c.source} câu nguồn hợp lệ + ${c.generated} câu tự sinh có nhãn riêng.</strong></p><p>${c.theory} câu lý thuyết cần ít nhất 7 đề để mỗi đề có tối đa 7 câu. ${c.calculation} câu tính toán nguồn chưa đủ các vị trí còn lại, nên bổ sung đúng ${c.generated} bài tính toán. Mỗi câu chỉ dùng một lần trong cả 7 đề.</p><p class="fine">Giữ nguyên chữ, số liệu và thứ tự lựa chọn theo bản chép bạn gửi; chưa có ảnh gốc để xác nhận các lỗi OCR. Câu cắt/lỗi được giữ riêng. Đề ghép có số thứ tự mới; mã R đối chiếu được vị trí nguồn.</p>`;
function setPanel(name){for(const id of ['homePanel','examPanel','archivePanel','auditPanel'])byId(id).hidden=id!==name;for(const [id,on] of [['examTab',name==='homePanel'||name==='examPanel'],['archiveTab',name==='archivePanel'],['auditTab',name==='auditPanel']])byId(id).setAttribute('aria-selected',on?'true':'false');}
function openExam(id){current=DATA.exams.find(e=>e.id===Number(id));if(!current)return;
 if(!progress.exams[current.id]){progress.exams[current.id]={answers:{},submitted:false,timed:byId('timedMode').checked,started:Date.now(),finished:null};save();}
 setPanel('examPanel');history.replaceState(null,'',`?exam=${current.id}`);renderExam();byId('examTitle').scrollIntoView({block:'start'});tick();
}
function renderExam(){const e=current,s=progress.exams[e.id];document.body.dataset.submitted=String(s.submitted);byId('examTitle').textContent=e.title+' · 20 câu';
 byId('questionList').innerHTML=e.ids.map((k,i)=>{const q=DATA.questions[k],a=s.answers[k],sol=q.solution;return `<article class="question" id="question-${i+1}" data-question="${k}"><div class="question-head"><h3>Câu ${i+1} <span class="badge ${q.generated?'generated':''}">${q.generated?'Tự sinh để đủ đề':'Nguồn · '+k}</span><span class="badge">${q.kind==='theory'?'Lý thuyết':'Tính toán'}</span></h3><button class="mark" data-mark="${k}" aria-pressed="${!!progress.marks[k]}">${progress.marks[k]?'★ Đã đánh dấu':'☆ Đánh dấu'}</button></div>${q.note?`<p class="fine">${esc(q.note)}</p>`:''}<div class="source-stem">${q.stemHtml}</div><fieldset class="options" style="border:0;padding:0"><legend class="fine">${s.submitted?'Đáp án đã khóa sau khi nộp':'Chọn một đáp án'}</legend>${q.options.map(o=>`<label class="option ${s.submitted?(o.label===sol.answer?'correct-option':o.label===a?'wrong-option':''):''}"><input type="radio" name="${k}" value="${o.label}" ${a===o.label?'checked':''} ${s.submitted?'disabled':''}><span><strong>${esc(o.sourceLabel||o.label)}.</strong> ${esc(o.text)}${s.submitted?(o.label===sol.answer?' <strong>✓ Đáp án đúng</strong>':o.label===a?' <strong>✕ Bạn đã chọn</strong>':''):''}</span></label>`).join('')}</fieldset>${s.submitted?`<p class="fine">${a?'Bạn chọn '+a:'Bạn bỏ trống'} · ${a===sol.answer?'Đúng':'Đáp án đúng: '+sol.answer}</p><section class="solution">${q.solutionHtml}</section>`:''}</article>`;}).join('');
 updateNav();renderScore();math(byId('questionList'));byId('downloadSolutions').hidden=!s.submitted;
}
function updateNav(){const s=progress.exams[current.id];byId('answeredCount').textContent=`Đã chọn ${Object.keys(s.answers).length}/20 câu`;
 byId('questionNav').innerHTML=current.ids.map((k,i)=>`<button data-jump="${i+1}" class="${s.submitted?(s.answers[k]===DATA.questions[k].solution.answer?'correct':'wrong'):s.answers[k]?'answered':''}" aria-label="Câu ${i+1}${s.answers[k]?', đã chọn '+s.answers[k]:', chưa chọn'}">${i+1}</button>`).join('');
}
function renderScore(){const e=current,s=progress.exams[e.id],el=byId('scorePanel');el.hidden=!s.submitted;if(!s.submitted)return;
 const right=score(e,s),blank=e.ids.filter(k=>!s.answers[k]).length;
 const groups=[['Lý thuyết',q=>q.kind==='theory'],['Tính toán',q=>q.kind==='calculation'],['Câu nguồn',q=>!q.generated],['Tự sinh',q=>q.generated]];
 el.innerHTML=`<strong>${right}/20 đúng · ${String(right/2).replace('.',',')}/10 điểm</strong><p>${20-right-blank} sai · ${blank} bỏ trống. Mỗi câu có trọng số bằng nhau.</p><p>${groups.map(([n,f])=>{const ids=e.ids.filter(k=>f(DATA.questions[k]));return `${n}: ${ids.filter(k=>s.answers[k]===DATA.questions[k].solution.answer).length}/${ids.length}`;}).join(' · ')}</p><p>Đọc lời giải ở từng câu bên dưới. Nút trang slide mở bản gốc ngay tại đây.</p>`;
}
function confirmAction(title,text,action){byId('confirmTitle').textContent=title;byId('confirmText').textContent=text;byId('confirmDialog').showModal();byId('confirmOk').onclick=()=>{byId('confirmDialog').close();action();};}
function finish(auto=false){if(!current)return;const s=progress.exams[current.id];if(s.submitted)return;s.submitted=true;s.finished=Date.now();save();renderExam();byId('scorePanel').scrollIntoView({block:'start'});if(auto)byId('timeLeft').textContent='Hết giờ · đã nộp';}
function tick(){if(!current||byId('examPanel').hidden)return;const s=progress.exams[current.id];if(s.submitted){byId('timeLeft').textContent='Đã nộp bài';return;}if(!s.timed){byId('timeLeft').textContent='Không giới hạn giờ';return;}const left=Math.max(0,45*60-Math.floor((Date.now()-s.started)/1000));byId('timeLeft').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(!left)finish(true);}
function download(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function archive(){const filter=byId('archiveFilter').value,term=byId('archiveSearch').value.toLocaleLowerCase('vi');const items=DATA.archive.filter(q=>(filter==='foreign'?q.kind==='foreign':filter==='variant'?q.status==='variant'||q.status==='fragment':q.kind!=='foreign'&&q.status!=='variant'&&q.status!=='fragment')&&(!term||(q.id+' '+q.raw+' '+q.note).toLocaleLowerCase('vi').includes(term)));
 byId('archiveCount').textContent=items.length+' mục';byId('archiveList').innerHTML=items.map(q=>`<details><summary><span class="badge ${q.kind==='foreign'?'problem':''}">${q.id}</span> ${q.kind==='foreign'?'Sai môn · chưa giải':q.status==='variant'||q.status==='fragment'?'Bản lặp / mảnh ghép':'Thiếu / lỗi / có giả thiết'} · ${esc(q.raw.replace(/[#*]/g,'').replace(/\s+/g,' ').slice(0,100))}…</summary><p class="fine">${esc(q.note)} · Dòng bản nguồn hiển thị: ${q.sourceRanges.map(x=>x.join('–')).join('; ')}</p><div class="raw source-stem">${q.rawHtml}</div>${q.kind==='foreign'?'<p class="notice">Giữ nguyên văn để đối chiếu. Chưa giải theo yêu cầu của bạn.</p>':`<section class="solution"><p class="notice">Phân tích riêng, không phải đáp án chấm thi chắc chắn. Giả thiết/sửa công thức được nêu rõ ở từng bước.</p>${q.solutionHtml}</section>`}</details>`).join('');
 byId('archiveList').querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)math(d);}));
}
function audit(){byId('auditContent').innerHTML=`<p>Nhận diện ${c.sourceRecords} câu hoặc mảnh nguồn: ${c.source} câu đưa vào đề; ${DATA.archive.filter(q=>q.kind!=='foreign').length} câu/mảnh thống kê giữ riêng; ${c.foreign} mục sai môn chưa giải.</p><p>Không xáo trộn lựa chọn. Trong từng đề, lý thuyết được đặt trước bài tính; các nhóm giữ thứ tự mã nguồn tăng dần. Các câu tính toán nguồn được chia đều sang 7 đề. Đây là bố cục ôn mới, không khẳng định là thứ tự của từng đề thi gốc.</p><p>Loại bản trùng hoàn toàn nếu có; bản chỉ đảo lựa chọn hoặc khác ký hiệu OCR của cùng câu cũng không đưa thêm lượt thi, nhưng lưu riêng để không làm mất dấu vết. Những câu khác dữ kiện hoặc khác đối tượng vẫn được giữ.</p><p>Ghép R118 từ phần hỏi, bảng và A/B ở dòng 1842–1857 với C/D ở dòng 1652–1653: dữ kiện 180 tỷ, tăng 25%, phần hỏi và A/B trùng khớp. Không tự đặt lại C/D.</p><p>Số câu tự sinh tối thiểu: 47 lý thuyết ÷ tối đa 7 mỗi đề → cần 7 đề. 7×20−89=${c.generated}. Câu thiếu lựa chọn, công thức mờ hoặc lỗi chưa xác định không được lấp bằng suy luận rồi trộn vào nguồn hợp lệ.</p><p>Lời giải do tôi tính và đối chiếu slide, không mặc định các chữ được tô trong review là đáp án đúng. Các lựa chọn chỉ có một chữ số thập phân được đối chiếu ở mức làm tròn đó, đồng thời ghi kết quả chính xác theo yêu cầu ở lời giải (R118, R138). R129 nêu riêng quy tắc làm tròn từng phép tính.</p><p class="fine">Slide dẫn theo số trang 1-based gồm cả bìa. Sách chương 1–4 →slide 1–4; sách 5–8 →slide 6–9. SHA-256 nguồn: ${DATA.sourceHash}.</p>`;
 byId('auditTable').innerHTML='<table><thead><tr><th>Đề</th><th>Lý thuyết</th><th>Tính toán</th><th>Nguồn</th><th>Tự sinh</th></tr></thead><tbody>'+DATA.exams.map(e=>`<tr><td>${e.title}</td><td>${e.theory}</td><td>${e.calculation}</td><td>${e.source}</td><td>${e.generated}</td></tr>`).join('')+'</tbody></table>';
}
byId('examGrid').onclick=e=>{const b=e.target.closest('[data-exam]');if(b)openExam(b.dataset.exam);};
byId('questionList').onchange=e=>{if(e.target.type!=='radio')return;const s=progress.exams[current.id];if(s.submitted)return;s.answers[e.target.name]=e.target.value;save();updateNav();};
byId('questionList').onclick=e=>{const b=e.target.closest('[data-mark]');if(b){const k=b.dataset.mark;progress.marks[k]=!progress.marks[k];b.setAttribute('aria-pressed',String(progress.marks[k]));b.textContent=progress.marks[k]?'★ Đã đánh dấu':'☆ Đánh dấu';save();}};
byId('questionNav').onclick=e=>{const b=e.target.closest('[data-jump]');if(b)byId('question-'+b.dataset.jump).scrollIntoView({behavior:'smooth',block:'start'});};
byId('submitExam').onclick=()=>{const s=progress.exams[current.id],blank=20-Object.keys(s.answers).length;confirmAction('Nộp '+current.title,blank?`Còn ${blank} câu chưa chọn. Nộp bài sẽ tính các câu này là bỏ trống và mở toàn bộ lời giải.`:'Nộp bài để chấm điểm, khóa lựa chọn và mở lời giải từng câu.',()=>finish());};
byId('confirmCancel').onclick=()=>byId('confirmDialog').close();
byId('restartExam').onclick=()=>confirmAction('Làm lại '+current.title,'Xóa lựa chọn và kết quả của riêng đề này; các đề khác và dấu đánh dấu vẫn giữ.',()=>{progress.exams[current.id]={answers:{},submitted:false,timed:byId('timedMode').checked,started:Date.now(),finished:null};save();renderExam();tick();});
byId('backHome').onclick=byId('examTab').onclick=()=>{setPanel('homePanel');history.replaceState(null,'','review-exams.html');home();};
byId('archiveTab').onclick=()=>{setPanel('archivePanel');archive();};byId('auditTab').onclick=()=>{setPanel('auditPanel');audit();};
byId('archiveFilter').onchange=archive;byId('archiveSearch').oninput=archive;
byId('exportProgress').onclick=()=>download('tien-do-7-de-thong-ke.json',JSON.stringify(progress,null,2),'application/json');
byId('importProgress').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const candidate=validateProgress(JSON.parse(await file.text()));confirmAction('Nhập tiến độ','Thay tiến độ của bộ 7 đề bằng tệp vừa chọn. Bạn có thể xuất tiến độ hiện tại trước khi xác nhận.',()=>{progress=candidate;save();home();setPanel('homePanel');current=null;});}catch(err){byId('saveNotice').textContent=err.message;}e.target.value='';};
byId('downloadSolutions').onclick=()=>{const s=progress.exams[current.id];if(!s.submitted)return;const parts=['# '+current.title+' — lời giải đầy đủ'];for(const [i,k] of current.ids.entries()){const q=DATA.questions[k],a=q.solution;parts.push(`\n## Câu ${i+1} — ${k}${q.generated?' — TỰ SINH ĐỂ ĐỦ ĐỀ':''}`,q.raw,'\n### '+a.result,a.lesson,...a.formulas.map(t=>'$$'+t+'$$'),...a.steps.map((t,i)=>(i+1)+'. '+t),...Object.entries(a.optionAnalysis).map(([l,t])=>'- '+l+': '+t),'Bẫy: '+a.traps.join('; '),'Slide: '+a.refs.join(', '));}download('de-'+current.id+'-thong-ke-loi-giai.md',parts.join('\n\n'));};
home();const requested=Number(new URLSearchParams(location.search).get('exam'));if(DATA.exams.some(e=>e.id===requested))openExam(requested);setInterval(tick,1000);

let modalDeck=null,modalPage=1;
document.getElementById('zoomImage').onclick=()=>{const im=document.querySelector('#modalBody img');if(!im)return;const large=im.dataset.large==='true';im.dataset.large=String(!large);im.style.width=large?'100%':Math.max(im.naturalWidth,750)+'px';document.getElementById('zoomImage').textContent=large?'Phóng lớn':'Vừa cửa sổ';};
function showImage(key,title){modalDeck=null;document.getElementById('modalTitle').textContent=title;document.getElementById('slideNav').hidden=true;document.getElementById('sourceFilename').textContent='Ảnh trích từ tài liệu nguồn; chữ và số liệu giữ nguyên.';document.getElementById('modalBody').innerHTML='';const im=document.createElement('img');im.src=DATA.assets[key];im.alt=title;document.getElementById('modalBody').append(im);const dlg=document.getElementById('sourceDialog');if(!dlg.open)dlg.showModal();}
function showSlide(deck,page){modalDeck=Number(deck);modalPage=Number(page);const source=DATA.sources.find(s=>s.chapter===modalDeck);if(!source||!DATA.slides[deck+':'+page])return;document.getElementById('modalTitle').textContent='Slide chương '+deck+' · trang '+page+' / '+source.slides;document.getElementById('sourceFilename').textContent=source.source;document.getElementById('slideNav').hidden=false;document.getElementById('slidePage').innerHTML=Array.from({length:source.slides},(_,i)=>'<option value="'+(i+1)+'" '+(i+1===Number(page)?'selected':'')+'>Trang '+(i+1)+'</option>').join('');document.getElementById('slidePrev').disabled=Number(page)===1;document.getElementById('slideNext').disabled=Number(page)===source.slides;document.getElementById('modalBody').innerHTML='';const im=document.createElement('img');im.src=DATA.assets[DATA.slides[deck+':'+page]];im.alt='Slide chương '+deck+', trang '+page;document.getElementById('modalBody').append(im);const dlg=document.getElementById('sourceDialog');if(!dlg.open)dlg.showModal();dlg.scrollTop=0;}
document.addEventListener('click',e=>{const ref=e.target.closest('[data-ref]');if(ref){const [d,p]=ref.dataset.ref.split(':');showSlide(d,p);}});document.getElementById('closeModal').onclick=()=>document.getElementById('sourceDialog').close();document.getElementById('slidePrev').onclick=()=>showSlide(modalDeck,modalPage-1);document.getElementById('slideNext').onclick=()=>showSlide(modalDeck,modalPage+1);document.getElementById('slidePage').onchange=e=>showSlide(modalDeck,Number(e.target.value));document.getElementById('sourceDialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const box=e.currentTarget.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)e.currentTarget.close();}});
